include:
    - ./pepper-middleware/docker-compose.yml
services:
    mosquitto:
        image: eclipse-mosquitto
        volumes:
        - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
        - ./mosquitto/data:/mosquitto/data
        ports:
        - "1883:1883"

        
    node-red:
        image: node-red
        volumes:
        # only show nodes of base, pepper and temi together with surveys
            - "./node-red/data:/data/"
            - "./node-red/nodes/base/:/nodes/base/:ro"
            - "./node-red/nodes/pepper/:/nodes/pepper/:ro"
            - "./node-red/nodes/temi/:/nodes/temi/:ro"  
            - "./node-red/settingsTemplate.js:/usr/src/node-red/settingsTemplate.js:ro"
            - ./node-red/answer_surveys:/usr/src/node-red/answer_surveys
        environment:
            # TODO: Check and delete possible unnecessary environment variables
            - "FLASK_DEBUG=${FLASK_DEBUG?error}"
            - "FLASK_PORT=${FLASK_PORT?error}"
            - "FLASK_PORT_PEPPER=${FLASK_PORT_PEPPER?error}"
            - "FLASK_IP=${FLASK_IP}"
            - "FLASK_IP_PEPPER=${FLASK_IP_PEPPER}"
            - "PYTHONUNBUFFERED=${PYTHONUNBUFFERED?error}"
            - "QI_LOG_LEVEL=${QI_LOG_LEVEL?error}"
            - "NODE_RED_PORT=${NODE_RED_PORT?error}"
            - "NODE_RED_PORT_PEPPER=${NODE_RED_PORT_PEPPER?error}"
            - "NODE_RED_LOG_LEVEL=${NODE_RED_LOG_LEVEL}"
            - "NODE_ENV=${NODE_ENV?error}"
            - "REST_SERVER_PORT=${REST_SERVER_PORT?error}"
            - "REST_LOG_LEVEL=${REST_LOG_LEVEL?error}"
            - "PEPPER_REST_SERVER_IP=${PEPPER_REST_SERVER_IP?error}"
            - "PEPPER_REST_SERVER_PORT=${PEPPER_REST_SERVER_PORT?error}"
            - "ROBOT_NAME=${ROBOT_NAME?error}"
            - "ROBOT_IP_SAWYER=${ROBOT_IP_SAWYER?error}"
            - "ROBOT_NAME_PEPPER=${ROBOT_NAME_PEPPER?error}"
            - "ROBOT_IP_PEPPER=${ROBOT_IP_PEPPER?error}"
            - "TEMI_PORT=${TEMI_PORT?error}"
            - "TEMI_ADDRESS=${TEMI_ADDRESS?error}"
            - "MQTT_PORT_PEPPER=${MQTT_PORT_PEPPER?error}"
            - "HOST_IP=${HOST_IP?error}"
            - "HOSTNAME=${HOSTNAME?error}"
            - "OPENAI_API_KEY=${OPENAI_API_KEY}"
            - "MQTT_BROKER_URL=${MQTT_BROKER_URL}"
            - "MQTT_BROKER_USERNAME=${MQTT_BROKER_USERNAME}"
            - "MQTT_BROKER_PASSWORD=${MQTT_BROKER_PASSWORD}"
            - TZ=Europe/Berlin
        network_mode: host
        restart: on-failure:5
        healthcheck:
            test: ["CMD", "curl --fail http://localhost:${NODE_RED_PORT}"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s

        depends_on:
            rest-server-pepper:
                condition: service_healthy

    
    videoserver:
        image: python:3.11-slim
        working_dir: /videos
        command: python -m http.server 8123 --bind 0.0.0.0
        volumes:
            - ./videos:/videos
        ports:
            - "8123:8123"
        restart: unless-stopped
